name: Build and Push Docker Image

permissions:
  id-token: write
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - docs/**

jobs:
  build:
    env:
      DEPLOY_TO_TEST: ${{ github.ref_type == 'branch' && secrets.RENDER_TEST_DEPLOY_URL != 'disabled' }}
      DEPLOY_TO_MAIN: ${{ github.ref_type == 'branch' && secrets.RENDER_MAIN_DEPLOY_URL != 'disabled' }}
    runs-on: depot-ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Depot
      uses: depot/setup-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Log in to Docker Hub
      if: ${{ github.ref_type == 'tag' && !contains(github.ref_name, '-rc') }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: depot/build-push-action@v1
      with:
        project: bbqjs4tj1g
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          ${{ github.ref_type == 'tag' && !contains(github.ref_name, '-rc') && format('docker.io/obot/{0}:{1}', github.event.repository.name, github.ref_name) || '' }}
        platforms: linux/amd64,linux/arm64

    - name: Setup crane
      uses: imjasonh/setup-crane@v0.4

    - name: Copy to latest tag
      if: ${{ github.ref_type == 'tag' && !contains(github.ref_name, '-rc') }}
      run: |
        crane tag ghcr.io/${{ github.repository }}:${{ github.ref_name }} latest
        crane tag docker.io/obot/${{ github.event.repository.name }}:${{ github.ref_name }} latest

    - name: Deploy to Test Render
      if: ${{ env.DEPLOY_TO_TEST == 'true' }}
      uses: joelwmale/webhook-action@2.4.1
      with:
        url: ${{ secrets.RENDER_TEST_DEPLOY_URL }}

    - name: Deploy to Main Render
      if: ${{ env.DEPLOY_TO_MAIN == 'true' }}
      uses: joelwmale/webhook-action@2.4.1
      with:
        url: ${{ secrets.RENDER_MAIN_DEPLOY_URL }}
